### ISSUE TITLE
HomeScreen

### ISSUE THREAD

**Issue by Mass-14** [EPFLSWENT2024G1/partagix#101]
Implement the HomeScreen according to the figma, with its ViewModel and tests.

**Comment by Mass-14** [comment]
At the end of sprint 4, most of the UI and the UI tests were done.
The viewmodel hasn't been started yet.

**Comment by KassFlute** [comment]
The home screen is kind of a combination of a preview from each screen so we decided to not implement a ViewModel for the home screen but use the ViewModels from each individual screens in it
