### ISSUE TITLE
Create LoanRequestManage screen

### ISSUE THREAD

**Issue by KassFlute** [EPFLSWENT2024G1/partagix#116]
We have a screen to borrow items to others, but not a screen to manage borrow requests to our own items.
This screen will be accessible from the "See All" button of the home screen and a preview of it will be visible on the home screen. 
Also, the inventory should have a shortcut to this screen, according to the figma design.

**Comment by AntoineBut** [comment]
This is stale and a duplicate. See Scrumboard for actual task.
