### ISSUE TITLE
Link images (database / ui)

### ISSUE THREAD

**Issue by Patrick-Pataky** [EPFLSWENT2024G1/partagix#128]
Observations:
- The DB model allows to download/upload images from the DB. 
- Each item has locally an image (hard-coded), currently not connected to the DB

**Your task:** 
- Connect the images from the DB with the local images. Please think about a nice default image, when there is no available image :)
- Don't forget to update InventoryViewItem (check for todos)
- Don't forget to update the Profile Picture (ViewAccount)

**Comment by AntoineBut** [comment]
After 70 commits over the last 2 weeks, we finally have functioning images on the user profile and the item UI! 
There are still places of the app where the images are missing, this will be a new task in the upcoming sprint. 

Thanks to all those who helped me, that was one hell of a task.
