### ISSUE TITLE
Add filters in inventory

### ISSUE THREAD

**Issue by KassFlute** [EPFLSWENT2024G1/partagix#174]
Implement filter functionalities in the inventory according to the figma (frontend and backend)
Also add tests to cover these new functionalities and keep the 80% line coverage.

hint: The figma filter design already exists -> checkout "Chips"

**Comment by AntoineBut** [comment]
This task was added to [this issue](https://github.com/orgs/EPFLSWENT2024G1/projects/1/views/1?pane=issue&itemId=63381617). Im closing it here so we don't have any duplicates.
