### ISSUE TITLE
Report bugs

### ISSUE THREAD

**Issue by Patrick-Pataky** [EPFLSWENT2024G1/partagix#197]
Spend 1 hour going through every user flow and search for any unexpected bugs. 

List them as comments under this task.

**Comment by Mass-14** [comment]
[] we can create an empty item, at least the name should be a mandatory field. 
[] Items in my inventory show my name, it's confusing.
[] on a list view of an item (home/loan/inventory screen), there is a "0" or a "n" at the left of the author name, this field is confusing we don't know what it shows.
