### ISSUE TITLE
Generate QR code design

### ISSUE THREAD

**Issue by Valentin889** [EPFLSWENT2024G1/partagix#218]
User Story 7
On StampScreen() :
- [x] add the BottomBar
- [x] remove "dimension" text
- add "Dimensions :" in the dimension dropdown (aborted, see comment below) 
- [x] remove "label" text
- [x] clean spacings

**Comment by Mass-14** [comment]
Adding "Dimension:" at the beginning of the label of the closed dropdown menu, resulted in a broken UI since the whole string didn't fit on a single line. Therefore this won't be implement (worsen the sreen instead of improving it).
