### ISSUE TITLE
Evaluate user design

### ISSUE THREAD

**Issue by Valentin889** [EPFLSWENT2024G1/partagix#219]
User story 10 and 11 on figma
- [ ] Not friend
- [ ] Comment

Add friends should not be implemented and display a message that's it's not done yet, the rest should be

**Comment by AntoineBut** [comment]
Due to all the unexpected difficulties I encountered on [this](https://github.com/orgs/EPFLSWENT2024G1/projects/1/views/1?pane=issue&itemId=61099517
), this task is postponed to sprint 9.
