### ISSUE TITLE
Fix location on create Item

### ISSUE THREAD

**Issue by Valentin889** [EPFLSWENT2024G1/partagix#223]
When we create or edit an item the location should be from a map and not a string, the display should be an adress and not a lat/lon string (the storage in the db can be the same as now)

**Comment by AntoineBut** [comment]
I wasn't sure I would have time for this, but I made it! Mostly thanks to the LocationPicker component made earlier this week in [this issue](https://github.com/orgs/EPFLSWENT2024G1/projects/1/views/1?filterQuery=sprints%3A%22Sprint+%238%22&pane=issue&itemId=62518125). Thank you @LozanoCyrielle , it works like a charm!
