### ISSUE TITLE
Home Screen bug fixes

### ISSUE THREAD

**Issue by AntoineBut** [EPFLSWENT2024G1/partagix#256]
There are know bugs on the Home Screen. Here is a partial list, though you may find more : 

- [x] Displayed borrows are duplicated
- [x] Scrolling closes the item detailed view
- [x] User is not always displayed correctly
- [x] _accepting a loan should close other loans requests for this item (moved to another task)_

Fix them to make our Home Screen more welcoming!

**Comment by Valentin889** [comment]
I believe  accepting a loan should close other loans requests for this item is a take for [#263](https://github.com/EPFLSWENT2024G1/partagix/issues/263)

**Comment by AntoineBut** [comment]
> I believe accepting a loan should close other loans requests for this item is a take for [#263](https://github.com/EPFLSWENT2024G1/partagix/issues/263)

Correct, you can ignore this bug in this task.

**Comment by LozanoCyrielle** [comment]
I fixed the duplicates for milestone 3 so, I've already done a part of the task :))
