### ISSUE TITLE
Fix inventory bugs

### ISSUE THREAD

**Issue by AntoineBut** [EPFLSWENT2024G1/partagix#258]
There are known bugs in the inventory screens : 

Borrowed items in loan state "ONGOING" should be displayed as well (and many in other cases, try to make something smart so that any loan that the users might want to be able to see appears!)

Search tools does no work as expected (it should in priority look at items whose names are matching the query)

Your task is to correct these bugs and look for more issues as well to make the inventory screen as fluent as possible.

**Comment by AntoineBut** [comment]
Also take care of [item filtering](https://github.com/orgs/EPFLSWENT2024G1/projects/1/views/1?pane=issue&itemId=61703181) as that task was left aside last sprint. I've updated the time estimate to take this into account.

**Comment by KassFlute** [comment]
I tested the borrowing workflow I found only 1 incoherent case and it's when I ask to borrow an item -> it gets accepted -> I start the loan => the item disappear from "Borrowed items" in my inventory.

**Comment by KassFlute** [comment]
InventoryViewModel is terrifying it will take me some time
