### ISSUE TITLE
Add UI for making a "bundled loan"

### ISSUE THREAD

**Issue by AntoineBut** [EPFLSWENT2024G1/partagix#264]
A bundled loan should be a list of items grouped in a single loan. They share everything (borrower, lender, time, loan state...)

This comes in a few steps : 

From the view account screen of someone else, the button "see inventory" should redirect to a new screen (ViewUserInventory or something like this) that displays the name of the user, all of this user's items as a list and a button "select". Check the Figma, work on it and look at how it is done in Inventory.kt as it should be very similar.

The button "select" allows to select a list of items, and another button "request items" that redirects to the StartLoanScreen. 

This task is only about making the new screen's UI and the navigation to that screen from the viewInventory screen. The functionality of making a bundled loan is done on [this issue](https://github.com/orgs/EPFLSWENT2024G1/projects/1/views/1?filterQuery=sprints%3A%22Sprint+%239%22&pane=issue&itemId=63426025). Work closely with the person doing this issue as you need to tell them what you need the viewModel to do (for example, you should be able to highlight on the UI the items that are selected by contouring them in another color or something like this)

**Comment by AntoineBut** [comment]
This task is postponed to newt sprint.

**Comment by Patrick-Pataky** [comment]
As discussed, we decided to not start this difficult functionality.
