### ISSUE TITLE
Change Loan Structure to take a list of items

### ISSUE THREAD

**Issue by AntoineBut** [EPFLSWENT2024G1/partagix#265]
Since we are adding "bundled loans", a loan should now be a list of items. Work closely with the person that will make the new UI Screens for making a bundled loan request to know how you will get the information about the loan.

First of all, adapt the places where the loans are currently used to take a List(item) instead of an item, make sure all previous functionalities remain operational. 

Then, allow for the new screen to make a "bundled loan"

**Comment by Patrick-Pataky** [comment]
As discussed, we decided to remove this feature.
