### ISSUE TITLE
Make the ViewModel for the new ViewUserInventory screen

### ISSUE THREAD

**Issue by AntoineBut** [EPFLSWENT2024G1/partagix#270]
See on [this issue](https://github.com/orgs/EPFLSWENT2024G1/projects/1/views/1?filterQuery=sprints%3A%22Sprint+%239%22&pane=issue&itemId=63383102) to know what the view model should do. Work closely with the person undertaking that task.

Your viewModel should allow to build the list of items that constitue the "bundled loan" at the user selects the items one by one. 

At the end, your ViewModel should compile all necessary information (such as having an instance of LoanViewModel or something similar) to request a loan for the list of items.

**Comment by AntoineBut** [comment]
As of this sprint, the View Model is only responsible for displaying the list of items belonging to the user we are watching.

Functionality for selecting items and staring a loan will be done on next sprint.

**Comment by Patrick-Pataky** [comment]
As discussed, we decided to not start this difficult functionality.
