### ISSUE TITLE
Implement the "Inventory Create Item" screen

### ISSUE THREAD

**Issue by AntoineBut** [EPFLSWENT2024G1/partagix#8]
Implement this functionality by following the Figma wireframe.

**Comment by zouyonghao** [comment]
Please update us on the status of this task, as sprint 2 is over.

**Comment by Mass-14** [comment]
@zouyonghao Hi, the task took a lot more time that planned since it needed development of components and the full corresponding viewmodel. Apart from the UI, it could only be started once the database setup was live (on Thursday), that's why I embarrassingly didn't delivered it on time.
